on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        ls -al
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print
      
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.4
      with:
        sftp: true
        host: asrez.com
        port: 22
        username: asrez
        password: ${{ secrets.FTP_PASSWORD }}
        remote_folder: '/home/asrez/public_html/test-react.maxbase.org/'
        local_folder: 'build/'
        cleanup: false
        include: '[ "*", "**/*" ]'
        exclude: '["node_modules/**", "_secret.php", ".github/**", ".git/**", "*.env"]'
        pasive: true
